config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  root "home#index"
  resources :books
  resources :authors, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, :email, presence: true
  validates :name, :email, length: { maximum: 50 }
  
  has_many :books

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def editable_by? editing_author
    !editing_author.nil? && editing_author.id == id
  end

end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, presence: true
  belongs_to :author

  has_one_attached :cover_image

  def editable_by? editing_author
    editing_author.id == author.id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update]

  def index
    @authors = Author.all
  end

  def show
  end

  def edit
    if @author.editable_by? current_author
      render :edit
    else
      redirect_to authors_url
    end
  end

  def update
    respond_to do |format|
      if @author.editable_by?(current_author) && @author.update(author_params) 
        format.html { redirect_to @author, notice: "Your information was updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unpocessable_entity }
      end
    end
  end

  private

    def set_author 
      @author = Author.find params[:id]
    end

    def author_params
      params.require(:author).permit(:name, :email)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_author!, except: [:index]
  before_action :set_book, only: [:show, :edit, :update, :destroy]


  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    respond_to do |format|
      unless current_author.nil?
        @book = Book.new(book_params)
        @book.author = current_author
        if @book.save
          format.html { redirect_to @book, notice: 'Book was successfully created.' }
          format.json { render :show, status: :created, location: @book }
        else
          format.html { render :new }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to books_url }
        format.json { render json: "", status: 401}
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.editable_by? current_author
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Book was successfully updated.' }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @book, notice: "Book cannot be edited." }
        format.json { render status: :bad_request}
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if @book.editable_by? current_author
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book cannot be deleted.' }
        format.json { render json: "Book cannot be deleted.", status: :bad_request }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id, :cover_image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @authors = Author.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% book.authors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

 <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <% if current_author.id == author.id %>
          <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<h3>Books:</h3>
<ul>
  <% @author.books.each do |book| %>
    <li><div class="book" style="background-image: url('<%= url_for(book.cover_image) %>')">
      <%= link_to book.title, book_path(book) %>
    </div></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_author_path(@author.id) if current_author.id == @author.id %>
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= link_to book.author.name, author_path(book.author) %></td>
        <td><%= link_to 'Show', book %></td>
        <% if current_author %>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path unless current_author.nil? %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= link_to @book.author.name, author_path(@book.author)  %>
</p>

<p>
  <strong>Cover Image:</strong>
  <% if @book.cover_image.attached? %>
    <%= image_tag url_for(@book.cover_image), { height: 100 } %>
  <% else %>
    No image uploaded.
  <% end %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<h3>Authors</h3>
<ul>
  <% @authors.each do |author| %>
    <li><%= author.name%></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active"><%= link_to "Home", root_path, { class: "nav-link" } %></li>
              <li class="nav-item"><%= link_to "Books", books_path, { class: "nav-link" } %></li>
              <li class="nav-item"><%= link_to "Authors", authors_path, { class: "nav-link" } %></li>
              <% unless current_author %>
                <li class="nav-item"><%= link_to "Sign in", new_author_session_path, { class: "nav-link" } %></li>
                <li class="nav-item"><%= link_to "Sign up", new_author_registration_path, { class: "nav-link" } %></li>
              <% else %>
                <li class="nav-item"><%= link_to "Hi, #{current_author.name}", author_path(current_author), { class: "nav-link"} %></li>
                <li class="nav-item"><%= link_to("Sign out", destroy_author_session_path, method: :delete, class: "nav-link") %></li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>

      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>

    </div>
  </body>
</html>